-- DropForeignKey
ALTER TABLE "ItemTODO" DROP CONSTRAINT "ItemTODO_listTODOId_fkey";

-- AddForeignKey
ALTER TABLE "ItemTODO" ADD CONSTRAINT "ItemTODO_listTODOId_fkey" FOREIGN KEY ("listTODOId") REFERENCES "ListTODO"("id") ON DELETE CASCADE ON UPDATE CASCADE;
